import os
from dotenv import load_dotenv

load_dotenv()

# Trading Settings
SYMBOLS = ["EURUSD=X", "GBPUSD=X", "USDJPY=X", "AUDUSD=X", "GC=F"]
NARRATIVE_TF = "1h"
STRUCTURE_TF = "15m"
ENTRY_TF = "5m" # Switched to 5m for better intraday consistency
SCALP_TF = "1m"

# INDICATORS
EMA_TREND = 200 # For H1 Trend
EMA_FAST = 20
EMA_SLOW = 50
RSI_PERIOD = 14
ATR_PERIOD = 14
ATR_AVG_PERIOD = 50

# LIQUIDITY
LIQUIDITY_LOOKBACK = 50 # bars
SWEEP_WICK_PERCENT = 0.60 # 60%

# DISPLACEMENT
DISPLACEMENT_BODY_PERCENT = 0.60 # 60%

# RSI THRESHOLDS
RSI_BUY_LOW = 25
RSI_BUY_HIGH = 40
RSI_SELL_LOW = 60
RSI_SELL_HIGH = 75

# TELEGRAM
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

# SESSION TIMES (UTC)
# London: 08:00 - 16:00
# NY: 13:00 - 21:00
LONDON_OPEN = 8
LONDON_CLOSE = 16
NY_OPEN = 13
NY_CLOSE = 21

# NEWS FILTER
NEWS_WASH_ZONE = 30 # Minutes before/after high-impact news
NEWS_IMPACT_LEVELS = ["High", "Medium"] # Impact levels to track

# SCORING
MIN_CONFIDENCE_SCORE = 9.0
